// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(smbcloud_authFFI)
import smbcloud_authFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_smbcloud_auth_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_smbcloud_auth_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSmbcloudAuthInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol SmbCloudAuthProtocol: AnyObject, Sendable {
    
    func buildAppleAuthorizationRequest(redirectUri: String, state: String?) throws  -> SmbCloudAppleAuthorizationRequest
    
    func buildOidcAuthorizationRequest(oidcClientId: String, redirectUri: String) throws  -> SmbCloudAuthorizationRequest
    
    func exchangeOidcCode(oidcClientId: String, redirectUri: String, code: String, codeVerifier: String) async throws  -> SmbCloudTokenResponse
    
    func getOidcUserinfo(accessToken: String, tenantId: String?) async throws  -> SmbCloudUserInfo
    
    func login(email: String, password: String) async throws  -> SmbCloudAccountStatus
    
    func logout(accessToken: String) async throws 
    
    func me(accessToken: String) async throws  -> SmbCloudUser
    
    func parseAppleCallbackUrl(callbackUrl: String, expectedState: String?) throws  -> SmbCloudAppleAuthSession
    
    func parseOidcCallbackUrl(callbackUrl: String) throws  -> SmbCloudCallbackPayload
    
    func removeAccount(accessToken: String) async throws 
    
    func signup(email: String, password: String) async throws  -> SmbCloudSignupResult
    
}
open class SmbCloudAuth: SmbCloudAuthProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_smbcloud_auth_fn_clone_smbcloudauth(self.pointer, $0) }
    }
public convenience init(environment: SmbCloudEnvironment, appId: String, appSecret: String) {
    let pointer =
        try! rustCall() {
    uniffi_smbcloud_auth_fn_constructor_smbcloudauth_new(
        FfiConverterTypeSmbCloudEnvironment_lower(environment),
        FfiConverterString.lower(appId),
        FfiConverterString.lower(appSecret),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_smbcloud_auth_fn_free_smbcloudauth(pointer, $0) }
    }

    

    
open func buildAppleAuthorizationRequest(redirectUri: String, state: String?)throws  -> SmbCloudAppleAuthorizationRequest  {
    return try  FfiConverterTypeSmbCloudAppleAuthorizationRequest_lift(try rustCallWithError(FfiConverterTypeSmbCloudAuthError_lift) {
    uniffi_smbcloud_auth_fn_method_smbcloudauth_build_apple_authorization_request(self.uniffiClonePointer(),
        FfiConverterString.lower(redirectUri),
        FfiConverterOptionString.lower(state),$0
    )
})
}
    
open func buildOidcAuthorizationRequest(oidcClientId: String, redirectUri: String)throws  -> SmbCloudAuthorizationRequest  {
    return try  FfiConverterTypeSmbCloudAuthorizationRequest_lift(try rustCallWithError(FfiConverterTypeSmbCloudAuthError_lift) {
    uniffi_smbcloud_auth_fn_method_smbcloudauth_build_oidc_authorization_request(self.uniffiClonePointer(),
        FfiConverterString.lower(oidcClientId),
        FfiConverterString.lower(redirectUri),$0
    )
})
}
    
open func exchangeOidcCode(oidcClientId: String, redirectUri: String, code: String, codeVerifier: String)async throws  -> SmbCloudTokenResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_exchange_oidc_code(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(oidcClientId),FfiConverterString.lower(redirectUri),FfiConverterString.lower(code),FfiConverterString.lower(codeVerifier)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_rust_buffer,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_rust_buffer,
            freeFunc: ffi_smbcloud_auth_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSmbCloudTokenResponse_lift,
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func getOidcUserinfo(accessToken: String, tenantId: String?)async throws  -> SmbCloudUserInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_get_oidc_userinfo(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(accessToken),FfiConverterOptionString.lower(tenantId)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_rust_buffer,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_rust_buffer,
            freeFunc: ffi_smbcloud_auth_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSmbCloudUserInfo_lift,
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func login(email: String, password: String)async throws  -> SmbCloudAccountStatus  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_login(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(email),FfiConverterString.lower(password)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_rust_buffer,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_rust_buffer,
            freeFunc: ffi_smbcloud_auth_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSmbCloudAccountStatus_lift,
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func logout(accessToken: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_logout(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(accessToken)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_void,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_void,
            freeFunc: ffi_smbcloud_auth_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func me(accessToken: String)async throws  -> SmbCloudUser  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_me(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(accessToken)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_rust_buffer,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_rust_buffer,
            freeFunc: ffi_smbcloud_auth_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSmbCloudUser_lift,
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func parseAppleCallbackUrl(callbackUrl: String, expectedState: String?)throws  -> SmbCloudAppleAuthSession  {
    return try  FfiConverterTypeSmbCloudAppleAuthSession_lift(try rustCallWithError(FfiConverterTypeSmbCloudAuthError_lift) {
    uniffi_smbcloud_auth_fn_method_smbcloudauth_parse_apple_callback_url(self.uniffiClonePointer(),
        FfiConverterString.lower(callbackUrl),
        FfiConverterOptionString.lower(expectedState),$0
    )
})
}
    
open func parseOidcCallbackUrl(callbackUrl: String)throws  -> SmbCloudCallbackPayload  {
    return try  FfiConverterTypeSmbCloudCallbackPayload_lift(try rustCallWithError(FfiConverterTypeSmbCloudAuthError_lift) {
    uniffi_smbcloud_auth_fn_method_smbcloudauth_parse_oidc_callback_url(self.uniffiClonePointer(),
        FfiConverterString.lower(callbackUrl),$0
    )
})
}
    
open func removeAccount(accessToken: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_remove_account(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(accessToken)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_void,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_void,
            freeFunc: ffi_smbcloud_auth_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    
open func signup(email: String, password: String)async throws  -> SmbCloudSignupResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_smbcloud_auth_fn_method_smbcloudauth_signup(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(email),FfiConverterString.lower(password)
                )
            },
            pollFunc: ffi_smbcloud_auth_rust_future_poll_rust_buffer,
            completeFunc: ffi_smbcloud_auth_rust_future_complete_rust_buffer,
            freeFunc: ffi_smbcloud_auth_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSmbCloudSignupResult_lift,
            errorHandler: FfiConverterTypeSmbCloudAuthError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAuth: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SmbCloudAuth

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SmbCloudAuth {
        return SmbCloudAuth(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SmbCloudAuth) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAuth {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SmbCloudAuth, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuth_lift(_ pointer: UnsafeMutableRawPointer) throws -> SmbCloudAuth {
    return try FfiConverterTypeSmbCloudAuth.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuth_lower(_ value: SmbCloudAuth) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSmbCloudAuth.lower(value)
}




public struct SmbCloudAppleAuthSession {
    public var accessToken: String
    public var refreshToken: String?
    public var email: String?
    public var name: String?
    public var provider: String
    public var providerAccountId: String
    public var state: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accessToken: String, refreshToken: String?, email: String?, name: String?, provider: String, providerAccountId: String, state: String?) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.email = email
        self.name = name
        self.provider = provider
        self.providerAccountId = providerAccountId
        self.state = state
    }
}

#if compiler(>=6)
extension SmbCloudAppleAuthSession: Sendable {}
#endif


extension SmbCloudAppleAuthSession: Equatable, Hashable {
    public static func ==(lhs: SmbCloudAppleAuthSession, rhs: SmbCloudAppleAuthSession) -> Bool {
        if lhs.accessToken != rhs.accessToken {
            return false
        }
        if lhs.refreshToken != rhs.refreshToken {
            return false
        }
        if lhs.email != rhs.email {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.provider != rhs.provider {
            return false
        }
        if lhs.providerAccountId != rhs.providerAccountId {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(accessToken)
        hasher.combine(refreshToken)
        hasher.combine(email)
        hasher.combine(name)
        hasher.combine(provider)
        hasher.combine(providerAccountId)
        hasher.combine(state)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAppleAuthSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAppleAuthSession {
        return
            try SmbCloudAppleAuthSession(
                accessToken: FfiConverterString.read(from: &buf), 
                refreshToken: FfiConverterOptionString.read(from: &buf), 
                email: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                provider: FfiConverterString.read(from: &buf), 
                providerAccountId: FfiConverterString.read(from: &buf), 
                state: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudAppleAuthSession, into buf: inout [UInt8]) {
        FfiConverterString.write(value.accessToken, into: &buf)
        FfiConverterOptionString.write(value.refreshToken, into: &buf)
        FfiConverterOptionString.write(value.email, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterString.write(value.provider, into: &buf)
        FfiConverterString.write(value.providerAccountId, into: &buf)
        FfiConverterOptionString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAppleAuthSession_lift(_ buf: RustBuffer) throws -> SmbCloudAppleAuthSession {
    return try FfiConverterTypeSmbCloudAppleAuthSession.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAppleAuthSession_lower(_ value: SmbCloudAppleAuthSession) -> RustBuffer {
    return FfiConverterTypeSmbCloudAppleAuthSession.lower(value)
}


public struct SmbCloudAppleAuthorizationRequest {
    public var authorizeUrl: String
    public var redirectUri: String
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(authorizeUrl: String, redirectUri: String, state: String) {
        self.authorizeUrl = authorizeUrl
        self.redirectUri = redirectUri
        self.state = state
    }
}

#if compiler(>=6)
extension SmbCloudAppleAuthorizationRequest: Sendable {}
#endif


extension SmbCloudAppleAuthorizationRequest: Equatable, Hashable {
    public static func ==(lhs: SmbCloudAppleAuthorizationRequest, rhs: SmbCloudAppleAuthorizationRequest) -> Bool {
        if lhs.authorizeUrl != rhs.authorizeUrl {
            return false
        }
        if lhs.redirectUri != rhs.redirectUri {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authorizeUrl)
        hasher.combine(redirectUri)
        hasher.combine(state)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAppleAuthorizationRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAppleAuthorizationRequest {
        return
            try SmbCloudAppleAuthorizationRequest(
                authorizeUrl: FfiConverterString.read(from: &buf), 
                redirectUri: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudAppleAuthorizationRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.authorizeUrl, into: &buf)
        FfiConverterString.write(value.redirectUri, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAppleAuthorizationRequest_lift(_ buf: RustBuffer) throws -> SmbCloudAppleAuthorizationRequest {
    return try FfiConverterTypeSmbCloudAppleAuthorizationRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAppleAuthorizationRequest_lower(_ value: SmbCloudAppleAuthorizationRequest) -> RustBuffer {
    return FfiConverterTypeSmbCloudAppleAuthorizationRequest.lower(value)
}


public struct SmbCloudAuthorizationRequest {
    public var authorizeUrl: String
    public var redirectUri: String
    public var state: String
    public var codeVerifier: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(authorizeUrl: String, redirectUri: String, state: String, codeVerifier: String) {
        self.authorizeUrl = authorizeUrl
        self.redirectUri = redirectUri
        self.state = state
        self.codeVerifier = codeVerifier
    }
}

#if compiler(>=6)
extension SmbCloudAuthorizationRequest: Sendable {}
#endif


extension SmbCloudAuthorizationRequest: Equatable, Hashable {
    public static func ==(lhs: SmbCloudAuthorizationRequest, rhs: SmbCloudAuthorizationRequest) -> Bool {
        if lhs.authorizeUrl != rhs.authorizeUrl {
            return false
        }
        if lhs.redirectUri != rhs.redirectUri {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.codeVerifier != rhs.codeVerifier {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authorizeUrl)
        hasher.combine(redirectUri)
        hasher.combine(state)
        hasher.combine(codeVerifier)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAuthorizationRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAuthorizationRequest {
        return
            try SmbCloudAuthorizationRequest(
                authorizeUrl: FfiConverterString.read(from: &buf), 
                redirectUri: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf), 
                codeVerifier: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudAuthorizationRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.authorizeUrl, into: &buf)
        FfiConverterString.write(value.redirectUri, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.codeVerifier, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuthorizationRequest_lift(_ buf: RustBuffer) throws -> SmbCloudAuthorizationRequest {
    return try FfiConverterTypeSmbCloudAuthorizationRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuthorizationRequest_lower(_ value: SmbCloudAuthorizationRequest) -> RustBuffer {
    return FfiConverterTypeSmbCloudAuthorizationRequest.lower(value)
}


public struct SmbCloudCallbackPayload {
    public var code: String
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(code: String, state: String) {
        self.code = code
        self.state = state
    }
}

#if compiler(>=6)
extension SmbCloudCallbackPayload: Sendable {}
#endif


extension SmbCloudCallbackPayload: Equatable, Hashable {
    public static func ==(lhs: SmbCloudCallbackPayload, rhs: SmbCloudCallbackPayload) -> Bool {
        if lhs.code != rhs.code {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(code)
        hasher.combine(state)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudCallbackPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudCallbackPayload {
        return
            try SmbCloudCallbackPayload(
                code: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudCallbackPayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.code, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudCallbackPayload_lift(_ buf: RustBuffer) throws -> SmbCloudCallbackPayload {
    return try FfiConverterTypeSmbCloudCallbackPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudCallbackPayload_lower(_ value: SmbCloudCallbackPayload) -> RustBuffer {
    return FfiConverterTypeSmbCloudCallbackPayload.lower(value)
}


public struct SmbCloudSignupResult {
    public var code: Int32?
    public var message: String
    public var userId: Int32?
    public var userEmail: String?
    public var userCreatedAt: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(code: Int32?, message: String, userId: Int32?, userEmail: String?, userCreatedAt: String?) {
        self.code = code
        self.message = message
        self.userId = userId
        self.userEmail = userEmail
        self.userCreatedAt = userCreatedAt
    }
}

#if compiler(>=6)
extension SmbCloudSignupResult: Sendable {}
#endif


extension SmbCloudSignupResult: Equatable, Hashable {
    public static func ==(lhs: SmbCloudSignupResult, rhs: SmbCloudSignupResult) -> Bool {
        if lhs.code != rhs.code {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        if lhs.userId != rhs.userId {
            return false
        }
        if lhs.userEmail != rhs.userEmail {
            return false
        }
        if lhs.userCreatedAt != rhs.userCreatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(code)
        hasher.combine(message)
        hasher.combine(userId)
        hasher.combine(userEmail)
        hasher.combine(userCreatedAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudSignupResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudSignupResult {
        return
            try SmbCloudSignupResult(
                code: FfiConverterOptionInt32.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                userId: FfiConverterOptionInt32.read(from: &buf), 
                userEmail: FfiConverterOptionString.read(from: &buf), 
                userCreatedAt: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudSignupResult, into buf: inout [UInt8]) {
        FfiConverterOptionInt32.write(value.code, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterOptionInt32.write(value.userId, into: &buf)
        FfiConverterOptionString.write(value.userEmail, into: &buf)
        FfiConverterOptionString.write(value.userCreatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudSignupResult_lift(_ buf: RustBuffer) throws -> SmbCloudSignupResult {
    return try FfiConverterTypeSmbCloudSignupResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudSignupResult_lower(_ value: SmbCloudSignupResult) -> RustBuffer {
    return FfiConverterTypeSmbCloudSignupResult.lower(value)
}


public struct SmbCloudTokenResponse {
    public var accessToken: String
    public var tokenType: String
    public var expiresIn: Int32?
    public var refreshToken: String?
    public var scope: String?
    public var idToken: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(accessToken: String, tokenType: String, expiresIn: Int32?, refreshToken: String?, scope: String?, idToken: String?) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.refreshToken = refreshToken
        self.scope = scope
        self.idToken = idToken
    }
}

#if compiler(>=6)
extension SmbCloudTokenResponse: Sendable {}
#endif


extension SmbCloudTokenResponse: Equatable, Hashable {
    public static func ==(lhs: SmbCloudTokenResponse, rhs: SmbCloudTokenResponse) -> Bool {
        if lhs.accessToken != rhs.accessToken {
            return false
        }
        if lhs.tokenType != rhs.tokenType {
            return false
        }
        if lhs.expiresIn != rhs.expiresIn {
            return false
        }
        if lhs.refreshToken != rhs.refreshToken {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        if lhs.idToken != rhs.idToken {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(accessToken)
        hasher.combine(tokenType)
        hasher.combine(expiresIn)
        hasher.combine(refreshToken)
        hasher.combine(scope)
        hasher.combine(idToken)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudTokenResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudTokenResponse {
        return
            try SmbCloudTokenResponse(
                accessToken: FfiConverterString.read(from: &buf), 
                tokenType: FfiConverterString.read(from: &buf), 
                expiresIn: FfiConverterOptionInt32.read(from: &buf), 
                refreshToken: FfiConverterOptionString.read(from: &buf), 
                scope: FfiConverterOptionString.read(from: &buf), 
                idToken: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudTokenResponse, into buf: inout [UInt8]) {
        FfiConverterString.write(value.accessToken, into: &buf)
        FfiConverterString.write(value.tokenType, into: &buf)
        FfiConverterOptionInt32.write(value.expiresIn, into: &buf)
        FfiConverterOptionString.write(value.refreshToken, into: &buf)
        FfiConverterOptionString.write(value.scope, into: &buf)
        FfiConverterOptionString.write(value.idToken, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudTokenResponse_lift(_ buf: RustBuffer) throws -> SmbCloudTokenResponse {
    return try FfiConverterTypeSmbCloudTokenResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudTokenResponse_lower(_ value: SmbCloudTokenResponse) -> RustBuffer {
    return FfiConverterTypeSmbCloudTokenResponse.lower(value)
}


public struct SmbCloudUser {
    public var id: Int32
    public var email: String
    public var createdAt: String
    public var updatedAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int32, email: String, createdAt: String, updatedAt: String) {
        self.id = id
        self.email = email
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

#if compiler(>=6)
extension SmbCloudUser: Sendable {}
#endif


extension SmbCloudUser: Equatable, Hashable {
    public static func ==(lhs: SmbCloudUser, rhs: SmbCloudUser) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.email != rhs.email {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(email)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudUser {
        return
            try SmbCloudUser(
                id: FfiConverterInt32.read(from: &buf), 
                email: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudUser, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.id, into: &buf)
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudUser_lift(_ buf: RustBuffer) throws -> SmbCloudUser {
    return try FfiConverterTypeSmbCloudUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudUser_lower(_ value: SmbCloudUser) -> RustBuffer {
    return FfiConverterTypeSmbCloudUser.lower(value)
}


public struct SmbCloudUserInfo {
    public var sub: String
    public var email: String?
    public var emailVerified: Bool?
    public var tenantId: UInt64?
    public var tenantSlug: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sub: String, email: String?, emailVerified: Bool?, tenantId: UInt64?, tenantSlug: String?) {
        self.sub = sub
        self.email = email
        self.emailVerified = emailVerified
        self.tenantId = tenantId
        self.tenantSlug = tenantSlug
    }
}

#if compiler(>=6)
extension SmbCloudUserInfo: Sendable {}
#endif


extension SmbCloudUserInfo: Equatable, Hashable {
    public static func ==(lhs: SmbCloudUserInfo, rhs: SmbCloudUserInfo) -> Bool {
        if lhs.sub != rhs.sub {
            return false
        }
        if lhs.email != rhs.email {
            return false
        }
        if lhs.emailVerified != rhs.emailVerified {
            return false
        }
        if lhs.tenantId != rhs.tenantId {
            return false
        }
        if lhs.tenantSlug != rhs.tenantSlug {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sub)
        hasher.combine(email)
        hasher.combine(emailVerified)
        hasher.combine(tenantId)
        hasher.combine(tenantSlug)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudUserInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudUserInfo {
        return
            try SmbCloudUserInfo(
                sub: FfiConverterString.read(from: &buf), 
                email: FfiConverterOptionString.read(from: &buf), 
                emailVerified: FfiConverterOptionBool.read(from: &buf), 
                tenantId: FfiConverterOptionUInt64.read(from: &buf), 
                tenantSlug: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SmbCloudUserInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sub, into: &buf)
        FfiConverterOptionString.write(value.email, into: &buf)
        FfiConverterOptionBool.write(value.emailVerified, into: &buf)
        FfiConverterOptionUInt64.write(value.tenantId, into: &buf)
        FfiConverterOptionString.write(value.tenantSlug, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudUserInfo_lift(_ buf: RustBuffer) throws -> SmbCloudUserInfo {
    return try FfiConverterTypeSmbCloudUserInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudUserInfo_lower(_ value: SmbCloudUserInfo) -> RustBuffer {
    return FfiConverterTypeSmbCloudUserInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SmbCloudAccountStatus {
    
    case notFound
    case ready(accessToken: String
    )
    case incomplete(errorCode: UInt32
    )
}


#if compiler(>=6)
extension SmbCloudAccountStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAccountStatus: FfiConverterRustBuffer {
    typealias SwiftType = SmbCloudAccountStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAccountStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notFound
        
        case 2: return .ready(accessToken: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .incomplete(errorCode: try FfiConverterUInt32.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SmbCloudAccountStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notFound:
            writeInt(&buf, Int32(1))
        
        
        case let .ready(accessToken):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(accessToken, into: &buf)
            
        
        case let .incomplete(errorCode):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(errorCode, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAccountStatus_lift(_ buf: RustBuffer) throws -> SmbCloudAccountStatus {
    return try FfiConverterTypeSmbCloudAccountStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAccountStatus_lower(_ value: SmbCloudAccountStatus) -> RustBuffer {
    return FfiConverterTypeSmbCloudAccountStatus.lower(value)
}


extension SmbCloudAccountStatus: Equatable, Hashable {}







public enum SmbCloudAuthError: Swift.Error {

    
    
    case Api(errorCode: Int32, message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudAuthError: FfiConverterRustBuffer {
    typealias SwiftType = SmbCloudAuthError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudAuthError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Api(
            errorCode: try FfiConverterInt32.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SmbCloudAuthError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Api(errorCode,message):
            writeInt(&buf, Int32(1))
            FfiConverterInt32.write(errorCode, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuthError_lift(_ buf: RustBuffer) throws -> SmbCloudAuthError {
    return try FfiConverterTypeSmbCloudAuthError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudAuthError_lower(_ value: SmbCloudAuthError) -> RustBuffer {
    return FfiConverterTypeSmbCloudAuthError.lower(value)
}


extension SmbCloudAuthError: Equatable, Hashable {}




extension SmbCloudAuthError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SmbCloudEnvironment {
    
    case dev
    case production
}


#if compiler(>=6)
extension SmbCloudEnvironment: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSmbCloudEnvironment: FfiConverterRustBuffer {
    typealias SwiftType = SmbCloudEnvironment

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SmbCloudEnvironment {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .dev
        
        case 2: return .production
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SmbCloudEnvironment, into buf: inout [UInt8]) {
        switch value {
        
        
        case .dev:
            writeInt(&buf, Int32(1))
        
        
        case .production:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudEnvironment_lift(_ buf: RustBuffer) throws -> SmbCloudEnvironment {
    return try FfiConverterTypeSmbCloudEnvironment.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSmbCloudEnvironment_lower(_ value: SmbCloudEnvironment) -> RustBuffer {
    return FfiConverterTypeSmbCloudEnvironment.lower(value)
}


extension SmbCloudEnvironment: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureSmbcloudAuthInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_smbcloud_auth_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_build_apple_authorization_request() != 20401) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_build_oidc_authorization_request() != 27410) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_exchange_oidc_code() != 62992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_get_oidc_userinfo() != 55608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_login() != 22565) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_logout() != 50854) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_me() != 14252) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_parse_apple_callback_url() != 36073) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_parse_oidc_callback_url() != 50343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_remove_account() != 59938) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_method_smbcloudauth_signup() != 1373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_smbcloud_auth_checksum_constructor_smbcloudauth_new() != 47975) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSmbcloudAuthInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all